@progi_Server_HostAddress = http://localhost:5181

###
POST {{progi_Server_HostAddress}}/pricecalculator/
Content-Type: application/json

{
  "BasePrice": 398,
  "VehicleType": "Common"
}

###
POST {{progi_Server_HostAddress}}/pricecalculator/
Content-Type: application/json

{
  "BasePrice": 5,
  "VehicleType": "Luxury"
}